#!/usr/bin/with-contenv bash

# empty config = fresh install (presumably)
if [ -z "$(ls -A /config)" ]; then
	# copy default config
	cp -r "/defaults/." "/config"

	# update permissions
	chown abc:abc -R /config
fi
